### ISSUE TITLE
Help with Decrypting Encrypted Obsidian Markdown Files

### ISSUE THREAD

**Issue by ghubliming** [mmiksaa/obsidian-protected-note#10]
I recently backed up some encrypted markdown files from Obsidian Vault. However, when I put them back into Obsidian, I can't seem to decrypt them. Unfortunately, I’m not a professional coder, and I'm struggling to figure out how to decrypt the files with my password.

Does anyone know how this plug-in might have encrypted these files, or can point me to the exact encryption method used? I’d like to write a Python script to decrypt the files, but I'm not sure where to start. Any guidance or examples would be really appreciated

**Comment by mmiksaa** [comment]
Hello! Is there any possible way how can i contact you except github or mail. I'd like to help you.

**Comment by ghubliming** [comment]
Hey, thanks a lot for your eagerness to help! I managed to solve it using TypeScript with Crypto.js. It seems like the Python package for AES decryption has some inconsistencies with the JS file (or maybe I didn't fully understand it). It also looks like one of the files might be corrupted during double encryption, but all my other notes decrypted safely. The TypeScript code was written by Claude, link: https://github.com/ghubliming/MarkdownDecryptor

**Comment by mmiksaa** [comment]
Good job! Glad that you were able to solve your problem.
