### ISSUE TITLE
file corrupt

### ISSUE THREAD

**Issue by CryptoAlchemik** [mmiksaa/obsidian-protected-note#12]
when I disable password and plugin my notes didn't decrypted. how I can decrypt it??

**Comment by yaira25** [comment]
Happened to me too, I disabled the plugin and the files remained encrypted!
Please help me decrypt them!!

**Comment by mmiksaa** [comment]
Hello, i'm currently working on it. If you have any problems please tell me because right now i'm updating my plugin.

How to fix your problem:
1)Enable password again
2)Reload Obsidian
3)Enter your password.

Please, never forget to make backups!

**Comment by yaira25** [comment]
I tried the solution you suggested at first glance, of course, and it didn't change the situation.

**Comment by mmiksaa** [comment]
Contact me through my telegram please. I'll try my best to help you!

**Comment by yaira25** [comment]
Unfortunately I don't have access to Telegram, I would be happy to contact you by email.
