### ISSUE TITLE
CWE-306 No authenication required to manage plugin

### ISSUE THREAD

**Issue by wheresalice** [mmiksaa/obsidian-protected-note#3]
There is no authentication required in order to configure or uninstall the plugin so any user with access to Obsidian can also uninstall the plugin to remove any restrictions.

**Comment by mmiksaa** [comment]
I'll fix it soon (if it's possible). Thanks for your suggestion.

**Comment by mmiksaa** [comment]
Hello. I didnt find the way how to make it possible. Obsidian doesnt allow to undo deletion the plugin. Do you know any possible way how to do that?
